Add controllers
sergej-d83/java-shareit pull request #2
Opened 2022-12-01 13:21 UTC by sergej-d83

2022-12-02 14:05 UTC, sergeymamonov requested changes

2022-12-02 14:05 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/dao/ItemDao.java
> +    Collection<Item> getItemsByUserId(int userId);
Здесь действительно необходимо отдавать интерфейс Collection? Это достаточно общий интерфейс, то есть это может быть и массив и множество.

2022-12-02 14:05 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        } else if (userDto.getEmail() == null) {
Проверку валидности емайла лучше перенести в сервис. Валидацию обычно делают в сервисе.

2022-12-02 14:05 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            throw new InvalidDataException("Неполноценные данные." + itemDto);
Введены неполноценные данные. А какие именно? И придется проверять ВСЕ поля. Лучше указать конкретно, в каком поле ошибка.

2022-12-03 11:12 UTC, sergej-d83 commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        } else if (userDto.getEmail() == null) {
Она же вроде в сервисе. Или что имеется ввиду?

2022-12-03 19:57 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        } else if (userDto.getEmail() == null) {
Да, извиняюсь, совсем не то написал. Валидацию лучше выносить в отдельный метод. Так бизнес логику в методе будет легче увидеть. А то сейчас 10 строк валидации и несколько строк основной логики.

2022-12-03 19:58 UTC, sergeymamonov approved these changes

2022-12-04 06:54 UTC, merged