Add docker
sergej-d83/java-shareit pull request #5
Opened 2023-01-17 06:47 UTC by sergej-d83

2023-01-18 21:11 UTC, sergeymamonov requested changes
ItemRequestServiceImpl в server, строка 96 - лучше эту фильтрацию сделать на стороне БД.

2023-01-18 21:11 UTC, sergeymamonov commented on gateway/Dockerfile
> +#RUN apk add --no-cache tzdata
В проекте не должно быть закомментированных строчек кода

2023-01-18 21:11 UTC, sergeymamonov commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +        return get("?state={state}&from={from}&size={size}", userId, parameters);
Лучше такие литералы выносить в константы или ресурсные файлы.

2023-01-18 21:11 UTC, sergeymamonov commented on server/Dockerfile
> +#RUN apk add --no-cache tzdata
В проекте не должно быть закомментированных строчек кода

2023-01-19 11:55 UTC, sergej-d83 commented
> ItemRequestServiceImpl в server, строка 96 - лучше эту фильтрацию сделать на стороне БД.

Не знаю как это сделать. Можно подсказку?

2023-01-19 19:07 UTC, sergeymamonov commented
Метод addItemsToRequests() получает список запросов, фильтрует эти запросы и делает определенную логику. Но передаваемые значения в метод addItemsToRequests() мы получаем из БД. Например, в методе getAllRequests. Но зачем запрашивать все из БД, а потом фильтровать в addItemsToRequests(). Запросите из БД только то, что нужно, и тогде не нужно будет фильтровать в addItemsToRequests(). Если что-то не будет получаться, можете написать в Пачке.

2023-01-19 19:07 UTC, sergeymamonov approved these changes

2023-01-20 07:28 UTC, merged